USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO;

CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW;
CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED;
CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART;
CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.LOGGING;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS PROD_WH 
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS PUBLIC_HEALTH_ROLE;

GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE PUBLIC_HEALTH_ROLE;

GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LOGGING TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ANALYST_ROLE;

GRANT USAGE ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE PUBLIC_HEALTH_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE PUBLIC_HEALTH_ROLE;

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE PUBLIC_HEALTH_ROLE;

GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LOGGING TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ENGINEER_ROLE;

GRANT ROLE DATA_ENGINEER_ROLE TO USER HATTAWAY7;
GRANT ROLE DATA_ANALYST_ROLE TO USER HATTAWAY7;
GRANT ROLE PUBLIC_HEALTH_ROLE TO USER HATTAWAY7;

ALTER USER HATTAWAY7 SET DEFAULT_ROLE = 'DATA_ENGINEER_ROLE';