USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS PH_DEMO_DEVELOPER_ROLE;
CREATE ROLE IF NOT EXISTS PH_DEMO_ANALYST_ROLE;


CREATE WAREHOUSE IF NOT EXISTS PH_DEMO_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;
CREATE DATABASE IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO;


GRANT USAGE ON WAREHOUSE PH_DEMO_WH TO ROLE PH_DEMO_DEVELOPER_ROLE;
GRANT USAGE ON WAREHOUSE PH_DEMO_WH TO ROLE PH_DEMO_ANALYST_ROLE;


GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE PH_DEMO_DEVELOPER_ROLE;
GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE PH_DEMO_ANALYST_ROLE;



USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO;
CREATE SCHEMA IF NOT EXISTS LANDING;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS DATAMART;
CREATE SCHEMA IF NOT EXISTS UTILITY;

 
GRANT ALL PRIVILEGES ON SCHEMA LANDING TO ROLE PH_DEMO_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA CURATED TO ROLE PH_DEMO_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DATAMART TO ROLE PH_DEMO_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA UTILITY TO ROLE PH_DEMO_DEVELOPER_ROLE;

-- Analyst gets read-only access
GRANT USAGE ON SCHEMA LANDING TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT USAGE ON SCHEMA CURATED TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DATAMART TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATAMART TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE PH_DEMO_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATAMART TO ROLE PH_DEMO_ANALYST_ROLE;

--- Give developer role to me (just one user in this demo account.)

GRANT ROLE PH_DEMO_DEVELOPER_ROLE TO USER HATTAWAY7;
GRANT ROLE PH_DEMO_ANALYST_ROLE TO ROLE PH_DEMO_DEVELOPER_ROLE;





