USE ROLE PH_DEMO_DEVELOPER_ROLE;
USE WAREHOUSE PH_DEMO_WH;
USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO; 

USE SCHEMA LANDING;
CREATE OR REPLACE TABLE CDC_PLACES_RAW (
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE ENV_HEALTH_RAW (
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

 
CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1;

CREATE OR REPLACE FILE FORMAT my_json_format
  TYPE = 'JSON';

CREATE OR REPLACE STAGE cdc_places_stage
  FILE_FORMAT = my_csv_format;
  
CREATE OR REPLACE STAGE env_health_stage
  FILE_FORMAT = my_json_format;

 
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE CDC_PLACES (
    LOCATION_ID INT,
    COUNTY VARCHAR,
    STATE VARCHAR(2),
    MEASURE VARCHAR,
    VALUE FLOAT,
    CONTACT_EMAIL VARCHAR -- This column will be masked
);

CREATE OR REPLACE TABLE ENV_HEALTH (
    REPORT_ID VARCHAR,
    LOCATION_NAME VARCHAR,
    POLLUTANT VARCHAR,
    LEVEL FLOAT,
    REPORTED_BY_EMAIL VARCHAR -- This column will be masked
);

 
USE SCHEMA DATAMART;
CREATE OR REPLACE TABLE COUNTY_HEALTH_METRICS (
    COUNTY VARCHAR,
    STATE VARCHAR(2),
    TOTAL_MEASURES INT,
    AVG_VALUE FLOAT
);