USE ROLE PH_DEMO_DEVELOPER_ROLE;
USE WAREHOUSE PH_DEMO_WH;
USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO; 


-- This policy masks email addresses unless the user has the 'DEVELOPER_ROLE'


USE SCHEMA UTILITY;
CREATE OR REPLACE MASKING POLICY email_mask AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('PH_DEMO_DEVELOPER_ROLE', 'ACCOUNTADMIN') THEN val
    ELSE '***-masked-***'
  END;

-- Apply masking policy to PII columns in the CURATED layer
USE SCHEMA CURATED;
ALTER TABLE IF EXISTS CDC_PLACES MODIFY COLUMN CONTACT_EMAIL SET MASKING POLICY UTILITY.email_mask;
ALTER TABLE IF EXISTS ENV_HEALTH MODIFY COLUMN REPORTED_BY_EMAIL SET MASKING POLICY UTILITY.email_mask;