USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO;
USE SCHEMA CURATED;

 
CREATE OR REPLACE MASKING POLICY address_mask AS (val STRING) RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE') THEN val
    WHEN CURRENT_ROLE() IN ('DATA_ANALYST_ROLE') THEN 
      CONCAT(LEFT(val, 10), '*** [MASKED] ***')
    ELSE '[REDACTED]'
  END;

 
CREATE OR REPLACE MASKING POLICY coordinate_mask AS (val FLOAT) RETURNS FLOAT ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE') THEN val
    WHEN CURRENT_ROLE() IN ('DATA_ANALYST_ROLE') THEN ROUND(val, 2)
    ELSE NULL
  END;

 
ALTER TABLE curated_environmental_data 
MODIFY COLUMN facility_address 
SET MASKING POLICY address_mask;

ALTER TABLE curated_health_indicators 
MODIFY COLUMN latitude 
SET MASKING POLICY coordinate_mask;

ALTER TABLE curated_health_indicators 
MODIFY COLUMN longitude 
SET MASKING POLICY coordinate_mask;

 
USE SCHEMA DATA_MART;

 
CREATE OR REPLACE MASKING POLICY population_mask AS (val INTEGER) RETURNS INTEGER ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE', 'DATA_ANALYST_ROLE') THEN val
    ELSE ROUND(val, -3)  
  END;

ALTER TABLE public_health_dashboard 
MODIFY COLUMN total_population 
SET MASKING POLICY population_mask;