USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO;
USE SCHEMA CURATED;

BEGIN
  BEGIN
    ALTER TABLE curated_environmental_data 
    MODIFY COLUMN facility_address 
    UNSET MASKING POLICY;
  EXCEPTION
    WHEN OTHER THEN
      NULL;
  END;
  
  BEGIN
    ALTER TABLE curated_health_indicators 
    MODIFY COLUMN latitude 
    UNSET MASKING POLICY;
  EXCEPTION
    WHEN OTHER THEN
      NULL;
  END;
  
  BEGIN
    ALTER TABLE curated_health_indicators 
    MODIFY COLUMN longitude 
    UNSET MASKING POLICY;
  EXCEPTION
    WHEN OTHER THEN
      NULL;
  END;
END;

USE SCHEMA DATA_MART;

BEGIN
  BEGIN
    ALTER TABLE public_health_dashboard 
    MODIFY COLUMN total_population 
    UNSET MASKING POLICY;
  EXCEPTION
    WHEN OTHER THEN
      NULL;
  END;
END;

USE SCHEMA CURATED;

BEGIN
  DROP MASKING POLICY IF EXISTS address_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

BEGIN
  DROP MASKING POLICY IF EXISTS coordinate_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

USE SCHEMA DATA_MART;

BEGIN
  DROP MASKING POLICY IF EXISTS population_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

USE SCHEMA CURATED;

CREATE MASKING POLICY address_mask AS (val STRING) RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE') THEN val
    WHEN CURRENT_ROLE() IN ('DATA_ANALYST_ROLE') THEN 
      CONCAT(LEFT(val, 10), '*** [MASKED] ***')
    ELSE '[REDACTED]'
  END;

CREATE MASKING POLICY coordinate_mask AS (val FLOAT) RETURNS FLOAT ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE') THEN val
    WHEN CURRENT_ROLE() IN ('DATA_ANALYST_ROLE') THEN ROUND(val, 2)
    ELSE NULL
  END;

USE SCHEMA DATA_MART;

CREATE MASKING POLICY population_mask AS (val INTEGER) RETURNS INTEGER ->
  CASE 
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER_ROLE', 'DATA_ANALYST_ROLE') THEN val
    ELSE ROUND(val, -3)
  END;

USE SCHEMA CURATED;

BEGIN
  ALTER TABLE curated_environmental_data 
  MODIFY COLUMN facility_address 
  SET MASKING POLICY address_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

BEGIN
  ALTER TABLE curated_health_indicators 
  MODIFY COLUMN latitude 
  SET MASKING POLICY coordinate_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

BEGIN
  ALTER TABLE curated_health_indicators 
  MODIFY COLUMN longitude 
  SET MASKING POLICY coordinate_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;

USE SCHEMA DATA_MART;

BEGIN
  ALTER TABLE public_health_dashboard 
  MODIFY COLUMN total_population 
  SET MASKING POLICY population_mask;
EXCEPTION
  WHEN OTHER THEN
    NULL;
END;