
USE ROLE PH_DEMO_DEVELOPER_ROLE;
USE WAREHOUSE PH_DEMO_WH;
USE DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO; 

USE SCHEMA UTILITY;
CREATE OR REPLACE TABLE PIPELINE_LOGS (
    LOG_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    PROCEDURE_NAME VARCHAR,
    STATUS VARCHAR,
    MESSAGE VARCHAR,
    ROW_COUNT INT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);