name: Deploy to Snowflake

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_DATABASE: PUBLIC_HEALTH_MODERNIZATION_DEMO

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    name: Validate SQL Scripts
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install snowflake-connector-python
        
    - name: Basic SQL validation
      run: |
        echo "✅ Repository structure:"
        find . -name "*.sql" -type f || echo "No SQL files found yet"
        find . -name "*.py" -type f || echo "No Python files found yet"
        echo "✅ Basic validation complete"

  deploy-to-prod:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: validate-sql
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Snowflake connector
      run: pip install snowflake-connector-python
      
    - name: Test Snowflake Connection
      run: |
        python -c "
        import snowflake.connector
        import os
        
        print('🔗 Testing Snowflake connection...')
        try:
            conn = snowflake.connector.connect(
                user=os.environ['SNOWFLAKE_USER'],
                password=os.environ['SNOWFLAKE_PASSWORD'],
                account=os.environ['SNOWFLAKE_ACCOUNT'],
                role='ACCOUNTADMIN',
                warehouse='COMPUTE_WH'
            )
            
            cursor = conn.cursor()
            cursor.execute('SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE()')
            result = cursor.fetchone()
            print(f'✅ Connected as: {result[0]} with role: {result[1]} using warehouse: {result[2]}')
            
            cursor.close()
            conn.close()
            print('🎉 Connection test successful!')
        except Exception as e:
            print(f'❌ Connection failed: {e}')
            raise
        "
        
    - name: Deploy Database Structure
      run: |
        python -c "
        import snowflake.connector
        import os
        
        try:
            conn = snowflake.connector.connect(
                user=os.environ['SNOWFLAKE_USER'],
                password=os.environ['SNOWFLAKE_PASSWORD'],
                account=os.environ['SNOWFLAKE_ACCOUNT'],
                role='ACCOUNTADMIN',
                warehouse='COMPUTE_WH'
            )
            
            cursor = conn.cursor()
            
            print('🏗️ Deploying database structure...')
            
            setup_commands = [
                'USE ROLE ACCOUNTADMIN',
                'USE WAREHOUSE COMPUTE_WH',
                'CREATE DATABASE IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO',
                'CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW',
                'CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED', 
                'CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART',
                'CREATE SCHEMA IF NOT EXISTS PUBLIC_HEALTH_MODERNIZATION_DEMO.LOGGING',
                'CREATE WAREHOUSE IF NOT EXISTS DEV_WH WITH WAREHOUSE_SIZE = \\'XSMALL\\' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE',
                'CREATE WAREHOUSE IF NOT EXISTS PROD_WH WITH WAREHOUSE_SIZE = \\'SMALL\\' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE',
                'CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE',
                'CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE',
                'CREATE ROLE IF NOT EXISTS PUBLIC_HEALTH_ROLE',
                'GRANT USAGE ON DATABASE PUBLIC_HEALTH_MODERNIZATION_DEMO TO ROLE DATA_ENGINEER_ROLE',
                'GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LANDING_RAW TO ROLE DATA_ENGINEER_ROLE',
                'GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.CURATED TO ROLE DATA_ENGINEER_ROLE',
                'GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.DATA_MART TO ROLE DATA_ENGINEER_ROLE',
                'GRANT ALL ON SCHEMA PUBLIC_HEALTH_MODERNIZATION_DEMO.LOGGING TO ROLE DATA_ENGINEER_ROLE',
                'GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DATA_ENGINEER_ROLE',
                'GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE DATA_ENGINEER_ROLE',
                'GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER_ROLE',
                'GRANT ROLE DATA_ENGINEER_ROLE TO USER HATTAWAY7',
                'GRANT ROLE DATA_ANALYST_ROLE TO USER HATTAWAY7',
                'GRANT ROLE PUBLIC_HEALTH_ROLE TO USER HATTAWAY7',
                'ALTER USER HATTAWAY7 SET DEFAULT_ROLE = \\'DATA_ENGINEER_ROLE\\''
            ]
            
            success_count = 0
            for cmd in setup_commands:
                try:
                    cursor.execute(cmd)
                    print(f'✅ {cmd[:60]}...')
                    success_count += 1
                except Exception as e:
                    print(f'⚠️ {cmd[:60]}... - {str(e)[:100]}')
            
            cursor.close()
            conn.close()
            print(f'🎉 Database structure deployment complete! {success_count}/{len(setup_commands)} commands succeeded')
            
        except Exception as e:
            print(f'❌ Database deployment failed: {e}')
            raise
        "
        
    - name: Deploy DDL Scripts
      run: |
        python scripts/deploy_ddl.py prod
      env:
        SNOWFLAKE_ROLE: ACCOUNTADMIN
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH

    - name: Deploy Masking Policies  
      run: |
        python scripts/deploy_masking_policies.py prod
      env:
        SNOWFLAKE_ROLE: ACCOUNTADMIN
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH

    - name: Deploy Stored Procedures
      run: |
        python scripts/deploy_procedures.py prod
      env:
        SNOWFLAKE_ROLE: ACCOUNTADMIN
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH

    - name: Test Complete Pipeline
      run: |
        python scripts/run_tests.py bootstrap
      env:
        SNOWFLAKE_ROLE: ACCOUNTADMIN
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH